name: abspy
channels:
  - conda-forge
dependencies:
  - python=3.11
  - colorlog
  - matplotlib
  - networkx
  - numpy
  - pyglet
  - rtree
  - sage=10.2
  - scikit-learn
  - scipy
  - tqdm
  - trimesh
  - pip:
      - abspy
      - open3d
