name: abspy_test
channels:
  - conda-forge
  - defaults
dependencies:
  - defaults::python=3.10
  - colorlog
  - matplotlib
  - networkx
  - numpy
  - pyglet
  - rtree
  - sage=10.0
  - scikit-learn
  - scipy
  - tqdm
  - trimesh
  - pip:
      - abspy
